### ISSUE TITLE
iOS 8 Unable to load Brackets

### ISSUE THREAD

**Issue by briancamarda** [Taerk/TioConverter2#1] opened 2016-10-21 21:27 UTC
The problem seems to be an issue with the back tick [`] character.
https://github.com/Taerk/TioConverter2/blob/master/main/tioconverter.bracket.js#L332

Replacing all of the back ticks with single quotes should fix this issue.

![screen shot 2016-10-21 at 5 25 17 pm](https://cloud.githubusercontent.com/assets/8310827/19612242/78150a1c-97b3-11e6-885a-508cca69da52.png)

**Comment by Taerk** [comment] 2016-10-25 03:17
As mentioned, it appears that the issue is related to iOS being incompatible with [string/template literals](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Template_literals#Browser_compatibility).

I'll look into making changes to have the site work on iOS 8 devices.

**Comment by Taerk** [comment] 2016-10-31 09:06
Fixed in 4d18a43

**Closed as completed by Taerk** 2016-10-31 09:06 UTC
